metadata:
  name: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster.example.com/argocd: enabled
  template:
    metadata:
      name: argocd-{{ name }}
    spec:
      source:
        repoURL: https://github.com/akselleirv/multi-cluster-deploments.git
        targetRevision: HEAD
        path: charts/argocd
        helm:
          releaseName: argocd
          valueFiles:
            - generated_values/{{ name }}_argocd.yaml
      destination:
        server: '{{ server }}'
        namespace: argocd
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
